//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcDistance.Client.CalcDist {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Point", Namespace="http://schemas.datacontract.org/2004/07/CalcDistance")]
    [System.SerializableAttribute()]
    public partial class Point : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcDist.ICalcDist")]
    public interface ICalcDist {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcDist/CalcDistance", ReplyAction="http://tempuri.org/ICalcDist/CalcDistanceResponse")]
        float CalcDistance(CalcDistance.Client.CalcDist.Point sPoint, CalcDistance.Client.CalcDist.Point ePoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcDist/CalcDistance", ReplyAction="http://tempuri.org/ICalcDist/CalcDistanceResponse")]
        System.Threading.Tasks.Task<float> CalcDistanceAsync(CalcDistance.Client.CalcDist.Point sPoint, CalcDistance.Client.CalcDist.Point ePoint);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcDistChannel : CalcDistance.Client.CalcDist.ICalcDist, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcDistClient : System.ServiceModel.ClientBase<CalcDistance.Client.CalcDist.ICalcDist>, CalcDistance.Client.CalcDist.ICalcDist {
        
        public CalcDistClient() {
        }
        
        public CalcDistClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcDistClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcDistClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcDistClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float CalcDistance(CalcDistance.Client.CalcDist.Point sPoint, CalcDistance.Client.CalcDist.Point ePoint) {
            return base.Channel.CalcDistance(sPoint, ePoint);
        }
        
        public System.Threading.Tasks.Task<float> CalcDistanceAsync(CalcDistance.Client.CalcDist.Point sPoint, CalcDistance.Client.CalcDist.Point ePoint) {
            return base.Channel.CalcDistanceAsync(sPoint, ePoint);
        }
    }
}
